name: Publish

on:
  push:
    tags:
      - "v**"

jobs:

  publish-luarocks:
    if: ${{ github.repository == 'zepinglee/LuaXML' }}
    name: Publish to LuaRocks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Set up dependencies
        run: luarocks install dkjson

      - name: Make entities module
        run: make luaxml-namedentities.lua

      - name: Parse semantic version
        id: semver
        run: echo version=$(lua .github/semver.lua ${{ github.ref_name }}) >> $GITHUB_OUTPUT

      - name: Make rockspec of new version
        run: luarocks new_version --tag ${GITHUB_REF_NAME#v} rockspecs/lzp-luaxml-dev-1.rockspec

      - name: Upload to LuaRocks
        run: luarocks upload --temp-key ${{ secrets.LUAROCKS_API_KEY }} lzp-luaxml-${GITHUB_REF_NAME#v}-1.rockspec
